services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak_book-net
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/main
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_DB_DATABASE: main
    depends_on:
      - postgres
    networks:
      - book-net
  postgres:
    image: postgres:16
    container_name: postgres_book-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book-net
  mail-dev:
    image: maildev/maildev:latest
    container_name: maildev_book-net
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - book-net
volumes:
  postgres_data:

networks:
  book-net:
    driver: bridge